### ISSUE TITLE
Quick question on utils.face_mesh_utils.py

### ISSUE THREAD

**Issue by Jaluco** [ibaiGorordo/Mediapipe-Halloween-Examples#1]
What's the data you got on "vertices"? where did it come from? I was trying to do a similar thing but am kinda lost now

**Comment by ibaiGorordo** [comment]
Hi,

In order to overlay one face into another, it needs to be done for every triangle in the mesh (look the image in the link below). This way you can estimate the affine transformation between the triangle in one face into the same triangle in the other face to transform all the pixels inside that triangle into the other image coordinates. So, to get those triangles you need to know the orders of the landmarks, which is what the vertices do. It gives you a map for which indices generate a triangle in the face mesh.

For example, the first 3 pair of points are:
`(127, 34),  (34, 139),  (139, 127)`, which means that the three segments in the first triangle are the segment between the landmarks 127-34, 34-139 and 139-127.

And here is the link with some information about where this info came from:
https://stackoverflow.com/questions/69858216/mediapipe-facemesh-vertices-mapping

It is a bit complicated, so let me know if you have more questions.
Ibai
